# Generated by Django 3.0 on 2021-02-14 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connects', models.IntegerField(default=10)),
                ('primary_text_color', models.CharField(blank=True, default='#ffffff', max_length=30, null=True)),
                ('primary_font_type', models.CharField(blank=True, choices=[('BebasNeue Bold', 'BebasNeue Bold'), ('BebasNeue Book', 'BebasNeue Book'), ('big_noodle_titling_oblique', 'big_noodle_titling_oblique'), ('big_noodle_titling', 'big_noodle_titling'), ('BRADHITC', 'BRADHITC'), ('CHILLER', 'CHILLER'), ('COLONNA', 'COLONNA'), ('comic', 'comic'), ('comicbd', 'comicbd'), ('cordia', 'cordia'), ('cordiab', 'cordiab'), ('cordiai', 'cordiai'), ('cordiau', 'cordiau'), ('cordiaub', 'cordiaub'), ('cordiaui', 'cordiaui'), ('cordiauz', 'cordiauz'), ('CURLZ___', 'CURLZ___'), ('FORTE', 'FORTE'), ('FREESCPT', 'FREESCPT'), ('FRSCRIPT', 'FRSCRIPT'), ('Gabriola', 'Gabriola'), ('HARNGTON', 'HARNGTON'), ('JOKERMAN', 'JOKERMAN'), ('MISTRAL', 'MISTRAL'), ('PRISTINA', 'PRISTINA'), ('RAGE', 'RAGE'), ('segoepr', 'segoepr'), ('segoeprb', 'segoeprb')], default='BebasNeue Bold', max_length=30, null=True)),
                ('primary_font_size', models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2, null=True)),
                ('brand_name', models.CharField(blank=True, default='@yourbrandname', max_length=30, null=True)),
                ('brand_name_font_type', models.CharField(blank=True, choices=[('BebasNeue Bold', 'BebasNeue Bold'), ('BebasNeue Book', 'BebasNeue Book'), ('big_noodle_titling_oblique', 'big_noodle_titling_oblique'), ('big_noodle_titling', 'big_noodle_titling'), ('BRADHITC', 'BRADHITC'), ('CHILLER', 'CHILLER'), ('COLONNA', 'COLONNA'), ('comic', 'comic'), ('comicbd', 'comicbd'), ('cordia', 'cordia'), ('cordiab', 'cordiab'), ('cordiai', 'cordiai'), ('cordiau', 'cordiau'), ('cordiaub', 'cordiaub'), ('cordiaui', 'cordiaui'), ('cordiauz', 'cordiauz'), ('CURLZ___', 'CURLZ___'), ('FORTE', 'FORTE'), ('FREESCPT', 'FREESCPT'), ('FRSCRIPT', 'FRSCRIPT'), ('Gabriola', 'Gabriola'), ('HARNGTON', 'HARNGTON'), ('JOKERMAN', 'JOKERMAN'), ('MISTRAL', 'MISTRAL'), ('PRISTINA', 'PRISTINA'), ('RAGE', 'RAGE'), ('segoepr', 'segoepr'), ('segoeprb', 'segoeprb')], default='BebasNeue Bold', max_length=50, null=True)),
                ('brand_name_font_size', models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2, null=True)),
                ('line_separation', models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2, null=True)),
                ('use_logo', models.BooleanField(blank=True, default=False, null=True)),
                ('logo_path', models.ImageField(blank=True, upload_to='logo')),
                ('logo_size', models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2, null=True)),
                ('resize', models.BooleanField(blank=True, default=True, null=True)),
                ('dim', models.BooleanField(blank=True, default=True, null=True)),
                ('greyscale', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
