# Generated by Django 3.0 on 2021-02-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dim',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resize',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='use_logo',
        ),
    ]
