# Generated by Django 3.0 on 2021-02-14 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210214_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brand_name_font_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='brightness',
            field=models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
