# Generated by Django 3.0 on 2021-02-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210214_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('BebasNeue Bold', 'BebasNeue Bold'), ('BebasNeue Book', 'BebasNeue Book'), ('big_noodle_titling_oblique', 'big_noodle_titling_oblique'), ('big_noodle_titling', 'big_noodle_titling'), ('BRADHITC', 'BRADHITC'), ('CHILLER', 'CHILLER'), ('COLONNA', 'COLONNA'), ('comic', 'comic'), ('comicbd', 'comicbd'), ('cordia', 'cordia'), ('cordiab', 'cordiab'), ('cordiai', 'cordiai'), ('cordiau', 'cordiau'), ('cordiaub', 'cordiaub'), ('cordiaui', 'cordiaui'), ('cordiauz', 'cordiauz'), ('CURLZ___', 'CURLZ___'), ('FORTE', 'FORTE'), ('FREESCPT', 'FREESCPT'), ('FRSCRIPT', 'FRSCRIPT'), ('Gabriola', 'Gabriola'), ('HARNGTON', 'HARNGTON'), ('JOKERMAN', 'JOKERMAN'), ('MISTRAL', 'MISTRAL'), ('PRISTINA', 'PRISTINA'), ('RAGE', 'RAGE'), ('segoepr', 'segoepr'), ('segoeprb', 'segoeprb')], default='English', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_image_downloaded',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_posts_created',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_posts_download',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
