# Generated by Django 3.0 on 2021-02-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210217_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number_of_posts_download',
            new_name='number_of_posts_downloaded',
        ),
    ]
