# Generated by Django 3.0 on 2021-02-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210217_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Portuguese', 'Portuguese')], default='English', max_length=30, null=True),
        ),
    ]
