# Generated by Django 3.0 on 2021-02-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210218_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ref_code_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
