# Generated by Django 3.0 on 2021-02-27 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20210224_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='brand_name_font_type',
            field=models.CharField(blank=True, choices=[('BebasNeue Bold', 'BebasNeue Bold'), ('BebasNeue Book', 'BebasNeue Book'), ('big_noodle_titling_oblique', 'big_noodle_titling_oblique'), ('big_noodle_titling', 'big_noodle_titling'), ('BRADHITC', 'BRADHITC'), ('CHILLER', 'CHILLER'), ('COLONNA', 'COLONNA'), ('comic', 'comic'), ('comicbd', 'comicbd'), ('cordia', 'cordia'), ('cordiab', 'cordiab'), ('cordiai', 'cordiai'), ('cordiau', 'cordiau'), ('cordiaub', 'cordiaub'), ('cordiaui', 'cordiaui'), ('cordiauz', 'cordiauz'), ('CURLZ___', 'CURLZ___'), ('FORTE', 'FORTE'), ('FREESCPT', 'FREESCPT'), ('FRSCRIPT', 'FRSCRIPT'), ('Gabriola', 'Gabriola'), ('HARNGTON', 'HARNGTON'), ('JOKERMAN', 'JOKERMAN'), ('MISTRAL', 'MISTRAL'), ('PRISTINA', 'PRISTINA'), ('RAGE', 'RAGE'), ('segoepr', 'segoepr'), ('segoeprb', 'segoeprb')], default='big_noodle_titling_oblique', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='brightness',
            field=models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_font_type',
            field=models.CharField(blank=True, choices=[('BebasNeue Bold', 'BebasNeue Bold'), ('BebasNeue Book', 'BebasNeue Book'), ('big_noodle_titling_oblique', 'big_noodle_titling_oblique'), ('big_noodle_titling', 'big_noodle_titling'), ('BRADHITC', 'BRADHITC'), ('CHILLER', 'CHILLER'), ('COLONNA', 'COLONNA'), ('comic', 'comic'), ('comicbd', 'comicbd'), ('cordia', 'cordia'), ('cordiab', 'cordiab'), ('cordiai', 'cordiai'), ('cordiau', 'cordiau'), ('cordiaub', 'cordiaub'), ('cordiaui', 'cordiaui'), ('cordiauz', 'cordiauz'), ('CURLZ___', 'CURLZ___'), ('FORTE', 'FORTE'), ('FREESCPT', 'FREESCPT'), ('FRSCRIPT', 'FRSCRIPT'), ('Gabriola', 'Gabriola'), ('HARNGTON', 'HARNGTON'), ('JOKERMAN', 'JOKERMAN'), ('MISTRAL', 'MISTRAL'), ('PRISTINA', 'PRISTINA'), ('RAGE', 'RAGE'), ('segoepr', 'segoepr'), ('segoeprb', 'segoeprb')], default='big_noodle_titling_oblique', max_length=30, null=True),
        ),
    ]
