# Generated by Django 3.0 on 2021-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210227_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='greyscale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
