# Generated by Django 3.0 on 2021-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20210227_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='greyscale',
            field=models.BooleanField(default=False),
        ),
    ]
