# Generated by Django 3.0 on 2021-03-01 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210228_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='brightness',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
