# Generated by Django 3.0 on 2021-03-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsmanager', '0002_masterpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterPassword',
        ),
    ]
