# Generated by Django 3.0 on 2021-03-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsmanager', '0004_auto_20210314_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='user',
            new_name='author',
        ),
    ]
