# Generated by Django 3.0 on 2021-03-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsmanager', '0005_auto_20210314_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterpassword',
            old_name='user',
            new_name='author',
        ),
    ]
